### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [gwenMB/l-m-montgomery_anne-of-the-island#1]
- [x] colophon.xhtml: wrap your name in a `<b epub:type="z3998:personal-name">` tag
- [x] Some of your editorial commits are going a bit farther than we normally go. I would probably revert the following:
1. 5e85b73 (her to herself)
2. ffaeb76 (missing word 'next')
3. 8b364a2 (adding the word 'a')
4. 0b12aaa (joining text to paragraphs) although some of the punctuation changes can be retained
- [x] In 70dedeb you turn "jog alone" to "jog along". I agree that this looks more plausible, but since it was repeated so many times I'd say you should leave it as printed. At the very least it should be its own editorial change and not a typo. 
- [x] Likewise in the same commit you replace "argued" with "augured", again a plausible change, but not necessary 
- [x] Typically we don't touch hypens beyond what modernize spelling does, and fixing any mismatches. I see at least some of the hyphens that you removed b5b25ab were added as part of some transcription "fixes" though (see next point)
- [x]  As Emma mentioned in the group chat, changing punctuation to match the scans is not typically something we do  since it requires a lot of effort and is very error prone. It looks like you modernized some of these changes away anyways. This should probably be tidied up (i.e. either dropped or at least squashed into a single commit). As it is it's confusing (to me at least) because it seems like you use Editorial to mean either your own change, or a reversion to the original transcription.
- [x] Some of the spelling changes in afc32c2 are converting from British to American spelling (e.g. criticise -> criticize). I thought that was the opposite of what you wanted to do? The scans use criticise. 
- [x] This has been discussed a few times in the group, but for some reason we  don't change "none the less" to "nonetheless", so that should also be reverted in afc32c2

**Comment by lukasbystricky** [comment]
Thinking about this some more, there's quite a bit to do. Since you put a lot of work into changing the transcription we should keep it, but it needs to be tidied up a bit. I would suggest the following:

1. Squash all the Transcription fixes into a single commit, with message like "Match transcription to scans"
2. Drop/undo any hyphenation changes other than those made by modernize spelling or need to fix inconsistent dashes (one exception I see is Jane-Andrews, I think you can remove the hyphen there)
3. Drop/undo the editorial commits/typo commits I mentioned above (or provide more context)
4. Since you're rebasing anyways you can drop the original cover image in 11af393

**Comment by gwenMB** [comment]
Thank you, Lukas.  This was a lot of changes to review.

1. I agree that "Match transcription to scans" is a better way to explain what I was doing in those commits.  I will change that in the commit messages.  However, I'm reluctant to squash them all down into one commit, given Alex's recent comment, "Commits are free and many small commits with distinct units of work are preferable to one very large commit that is hard to untangle."  Why do you feel that they should be squashed into a single commit?

I am aware that Standard Ebooks doesn't usually go over the differences between the page scans and transcription in such detail.  I failed to find a transcription that matched the page scans. I didn't realize just how different the transcription was from the page scans until long after I put in a lot of work. I had trouble keeping track of which differences between the two were "correct", so I went through and did a very detailed review of every line of the book looking for changes.  I did this by dropping the OCR output from anneofisland1920mont_djvu.txt over the top of my xhtml and using "git diff --color-words" to highlight differences, which I then visually verified by looking at the page scans and ignoring OCR mistakes.

So at that point, I had an updated transcription that closely matched the page scans.   Any changes made after that point that weren't formatting/semantics, I considered as "Editorial".  Even if the change had been part of the Bantam/FadedPage transcription. This is why you see things from Bantam/FadedPage that I took out of the book in a "Transcription fixes" commit and later changed back as part of and "Editorial" commit.

2. Regarding, "Drop/undo any hyphenation change," I would like you to clarify.  I'm not sure whether you want me to back out hyphen changes made as part of matching the transcription to the scans (within commits 6c22765-08d9bf).  I think you are asking me to only back out hyphen changes after this point, in other words, the ones marked Editorial (unless it is part of the modernize-spelling script or fix inconsistent dashes).

3. Regarding "Drop/undo the editorial commits/typo commits I mentioned above (or provide more context)", I will do so over the next few days.


4. I will replace the original cover image, as requested.  And also fix the Colophon info that I missed. The painting is by the same artist, but the year and name of the painting are different.

**Comment by lukasbystricky** [comment]
I think that what Alex meant by that is that it's important to avoid merge commits because those can be really hard to read. The main point is to keep commits "small" in the sense that they're independent units of work. For instance all the commits for matching the scans can be squashed into one commit because they're not independent. There's no scenario where we'd want to revert only some of them. Either we revert all of them or none of them (in our case none of them), so they might as well be a single commit. On the other hand it's a good idea to keep the editorial commits as separate commits since it is possible that we may decide to drop some but not all of them.  

It doesn't really matter, but in this case squashing those commits would make history more clear. If you don't want to do it though it's not a must. 

For point 2, you can keep whatever changes (including hyphenation) you made to the transcription to match the scans. That's now the base transcription; it's as if the original never existed. From that point on drop any changes in hyphenation (aside from the cases I listed).

**Comment by gwenMB** [comment]
I'm working on branch "reviewfix" for now. Will follow up with squashing and changing commit messages tomorrow.

### Colophon fixed.
* e3642ad Fix colophon, personal-name semantics and artwork info

### Removed suggested editorial commits, while leaving in the punctuation change.
* 9b4f261 Revert "[Editorial] replaced 'her' with 'herself'"
* 22f198f Revert "[Editorial] missing word 'next.'"
* ddb88e1 Revert "[Editorial] added the word 'a' in 'ever a Sophomore'"
* cee355f Partial Revert "[Editorial] Should not have new paragraph in middle of sentence"

### For commit 70dedeb I spit them out into individual commits.  
* 85c372a Revert "[Editorial] Fix typos"
* 6f92e1d [Editorial] Fix typo, chocolatee -> chocolate
* 4f83157 [Editorial] Fix typo, unmanagable -> unmanageable
* e980cc9 [Editorial] Fix typo, household gods  -> household goods
* 68a6e78 [Editorial] Fix typo, Jog alone -> Jog along
* 65c4e4d [Editorial] Fix typo, wedding tower -> wedding tour
* 595b0f0 [Editorial] Fix typo, argured -> augured

Note 1: I feel strongly that "Jog along" is correct here, given the wider context.  [In chapter 30](https://archive.org/details/anneofisland1920mont/page/248/mode/2up?q=mare), the character Amelia Skinner is talking to Anne while driving her in a horse-and-buggy. She frequently interrupts herself to talk to the horse, saying "Jog along, black mare."  This happens 12 times.  Pages 246, 247, and 249 each have "along" three times each.  Page 248 has "alone" three times. Maybe a different person typset page 248? I'm confident it is a typo.

Note 2: I believe you misread "argured" as "argued". In the page scans, the book has "argured," which is not in the dictionary.  Although both "argued" and "augured" are reasonable corrections, I think "augured" is a better fit because it has the sense of foretelling, or predicting the future. Also, [according to](https://books.google.com/ngrams/graph?content=augured+well%2Cargued+well&year_start=1800&year_end=2019&corpus=en-GB-2019&smoothing=3) Google Ngram, "augured well" shows up about five times as often as the phrase "argued well," although that doesn't tell us anything about the context.
> "She could do good, if not noble, work as a teacher; and the success her little sketches were beginning to meet with in certain editorial sanctums *argured* well for her budding literary dreams."

### Removed "modernize hyphenation" changes as requested.  
* f1f0c1a Revert "[Editorial] Modernize hyphenation"
* 67410c7 [Editorial] Use consistent hyphens, Jane-Andrews -> Jane Andrews

Note 1: Commit faa5c64 "Modernize hyphenation, prayer-meeting -> prayer meeting" is kept due to inconsistent hyphenation, but I will change the commit message to reflect this.

Note 2: I'm not sure about removing the "Jane-Andrews" hyphen, given that we are not removing all the other ones.  "Jane Andrews" is a character's name, but in this one sentence, her name is a adjective for the word "tale." The publisher would use hyphens to connect multi-word adjectives preceding a noun.  Context: Anne and her friend Stella are reading stories that Anne and her other friends (including Jane) wrote when they were much younger, meanwhile, the cat Rusty is sleeping on one of the stories (Jane's). Should I keep the hyphen here?
> ["[The cat slept] curled up on a Jane-Andrews tale of a beautiful maiden..."](https://archive.org/details/anneofisland1920mont/page/278/mode/2up?q=Jane-Andrews)

### Removed the spelling changes as requested (dropped "criticize" and "nonetheless") and split the remaining changes into their own commits.
* 7acaa32 Revert "[Editorial] Modernize spelling, various"
* b64f9f2 [Editorial] Modernize spelling, near by -> nearby
* 43575ee [Editorial] Modernize spelling, quartette -> quartet
* bd9aaee [Editorial] Modernize spelling, patch work -> patchwork
* 3a589d8 [Editorial] Modernize spelling, dumbfoundered -> dumbfounded
* 857184e [Editorial] Modernize spelling, stupified -> stupefied

Note: I had changed "criticise" to "criticize" because various dictionaries say that both variants are valid British spellings and the Google Ngram viewer [shows](https://books.google.com/ngrams/graph?content=criticise%2C+criticize&year_start=1800&year_end=2019&corpus=en-GB-2019&smoothing=3) "criticize" as being more popular in British works as of about 1990.

**Comment by gwenMB** [comment]
### Two additional changes

#### 1. Removed an additional editorial commit
* eb0ccb8 Revert "[Editorial] missing word 'to'"

The reasoning for this change was that it was the same type of change as the others that you said were going a bit farther than we normally go.

#### 2. Removed the punctuation/paragraph changes in "Match transcription to scans"
* 437c19d Revert "Transcription fixes, split paragraph in Ch 10"
* e2cfa9a Revert "[Editorial] Should not have new paragraph in middle of sentence"
* c90ae66 Revert "Partial Revert "[Editorial] Should not have new paragraph in middle of sentence""

Now the changes in "Match transcription to scans" are just spelling, hyphenation, and italics. No punctuation or paragraph breaks.  This had a couple of side effects downstream, allowing me to fully revert commit https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/0b12aaa12328cdfc0a4a1079be0285c904f62d20

### Rebase complete
- squashed commits (lots of commits, more than you asked for)
- dropped editorial commits that were reverted
- changed commit messages to be more clear
- changed order of commits to group like things together

The log looks very different, but there are no code differences between "master" and "reviewfix" branches

### Review #1 Complete
I believe that I have addressed all the issues that you found during the first review. The repository is ready for a second review.
