### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by lukasbystricky** [gwenMB/l-m-montgomery_anne-of-the-island#2]
This looks much better! I'm glad you decide the squash the transcription fixes, it makes it a lot easier to read. I think your explanations about the editorial changes make sense. It might be good to include the information in the commit description in cases where it's not clear. 

A couple more small things:

- [x] For 862d42a, do you know if this change has been made in other printings? I agree with your logic, but it does seem like a large change and if no one else has corrected it I'd be hesitant to do it. We can always ask Alex.
- [x] There's a few instances of italics being added to short story titles. Per SEMOS [8.2.11.3](https://standardebooks.org/manual/1.7.4/8-typography#8.2.11.3) short story titles should be quoted, not italicized. You can wrap them in a span tag to keep the semantics.

**Comment by gwenMB** [comment]
Yes, for 862d42a this change is often made on newer books. A [search ](https://archive.org/search?query=title%3A%28anne+of+the+island%29+AND+mediatype%3A%28texts%29+AND+ninth&sin=TXT&sort=-date) of books hosted on the Internet Archive shows ten different versions of the book that include this change (the search shows 12 hits, but the oldest three are duplicates). The Internet Archive has 16 copies of Anne of the Island that are English language texts published after 1980. Nine of the sixteen books have this change.

I did not keep italics on short story titles.  Things that remained as italics in the final commit were ships (Shannon, Cheasapeake, and Lawrence), magazines (Canadian Woman, and Youth’s Friend), a book (Pickwick Papers), a newspaper (Daily News), foreign words, and graphemes. The two short stories ("Averil’s Atonement" and "My Graves") had their italics removed and were quoted and semanticated within a span tag in [7eca4c7 - Italics](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/7eca4c785091eed3c943b7230fafb81a6697259f). However, I did just notice that I did not semanticate "Averil's Atonement" in the header for chapter 12, so that needs to be fixed.

But maybe you were expecting to see the work done in the earlier commit [b4d063a - Manually add additional semantics](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/b4d063afaf8377cf099312f656c7a0df7a70810d)?  I will squash these two commits together.

So here is my todo list:
- [x] Semanticate chapter 12 header, "Averil's Atonement."
- [ ] Squash together the three commits containing manual semantics changes (7eca4c7, b4d063a, and the new one)
- [x] Add explanatory commit messages to "Jog along" and "augured".  The commit "nine children, so tenth -> ninth" already has an explanation.  Are there others that I should explain more?

**Comment by lukasbystricky** [comment]
Ok great, then we can keep that change. And yes, you're right about the italics. I was looking at an earlier commit, sorry about that. 

The todo list looks good, but I don't think you need to squash together all the semantics changes, unless you really want to. Having a perfect history isn't necessary. The reason I asked you to squash the transcription changes together was because there was just so many of them. The description for the nine children change is good, but you should also mention that later printings also make this correction. 

I had one other question. In a36fe3b you removed some added commas. Did you intentionally not squash that into b10673f?

**Comment by gwenMB** [comment]
Allright, rather than squashing the three commits together, I renamed them as ["Manually add additional semantics, abbreviations"](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/9387e727f47986c33620d3ff758ba99d2c974da1) and ["Manually add additional semantics, Italics"](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/32509d5e425f9b8fb6e683d9c2c270bdef518666) and squashed the third commit that semanticates chapter 12's header into the "Italics" commit.

I updated commit messages for "[Jog along](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/dbef13a112164e5e9f4d854bc4b1930b276d3e5a)", "[augured](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/bf4c5f0d2b27a6cf01cc5460049e25e9bb15a17c)", and "[ninth](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/10dda37233afee5d2579d5940a045ee8ed94c69d)".

Yes, I intentionally did not include this change with the bigger "[Match transcription to scans](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/b10673fc59c172dd3bb13fa896988c45f9f81810)" because there was some discussion about whether or not to do the change in the google-groups email thread, and I wanted it to be easy to revert that change if necessary.  

I think I'm done with this set of changes.  It is ready for you to take another look.

**Comment by lukasbystricky** [comment]
Ok, but the decision was to follow the scans. So as long as that's the case we're not going to want to revert getting rid of the extra commas. Unless I'm misunderstanding something (always a possibility) I would squash them together. 

One final thing I missed earlier. We also (for some reason, this has been discussed in the group) don't modernize "worth while" to worthwhile. So commit 6a8b0e7 should be dropped. 

Otherwise looks good. Great job with the rebasing.

**Comment by gwenMB** [comment]
Squashed [Match transcription to scans](https://github.com/gwenMB/l-m-montgomery_anne-of-the-island/commit/e4590e7de17656009b30a612b7511ea6e45b6510) together. Dropped the "worthwhile" commit.

Changes have been pushed to master, ready for review.

**Comment by lukasbystricky** [comment]
Looks good to me!

**Comment by gwenMB** [comment]
Thank you, Lukas! I appreciate your help reviewing this book.
